services:
  mysql:
    container_name: mysql-bmUser
    image: mysql:9.2
    environment:
      - MYSQL_DATABASE=bmUser
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

